const EMAIL_MAX_LEN = "120";
const PASSWORD_MAX_LEN = "25";
const FIRST_NAME_MAX_LEN = "25";
const LAST_NAME_MAX_LEN = "25";
const USERNAME_MAX_LEN = "25";

const EMAIL_MIN_LEN = "5";
const PASSWORD_MIN_LEN = "8";
const FIRST_NAME_MIN_LEN = "3";
const LAST_NAME_MIN_LEN = "2";
const USERNAME_MIN_LEN = "5";

export const VALIDATION_LENGTH = {
  EMAIL_MAX_LEN,
  PASSWORD_MAX_LEN,
  FIRST_NAME_MAX_LEN,
  LAST_NAME_MAX_LEN,
  USERNAME_MAX_LEN,
  EMAIL_MIN_LEN,
  PASSWORD_MIN_LEN,
  FIRST_NAME_MIN_LEN,
  LAST_NAME_MIN_LEN,
  USERNAME_MIN_LEN,
};
